# Generated by Django 4.2.3 on 2023-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='location',
        ),
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
